#!/bin/dash

mutetoggle () {
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    mstate=$(pactl get-sink-mute @DEFAULT_SINK@)
    voll=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '/Volume: / {print $5,$12}')
}

voldown () {
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    voll=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '/Volume: / {print $5,$12}')
    mstate=$(pactl get-sink-mute @DEFAULT_SINK@)
}

volup () {
    pactl set-sink-volume @DEFAULT_SINK@ +5%
    voll=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '/Volume: / {print $5,$12}')
    mstate=$(pactl get-sink-mute @DEFAULT_SINK@)
}

popupinfo () {
    notify-send -t 5000 -h string:x-canonical-private-synchronous:my-notification \
        "Audio Mute yes/no & volume down/up" \
        "Audio $mstate  |  Volume: $voll"
}

case $1 in
    mtgl)
        mutetoggle
        popupinfo
        ;;
    down)
        voldown
        popupinfo
        ;;
    up)
        volup
        popupinfo
        ;;
esac
